### ISSUE TITLE
TD_RvNN pytorch version

### ISSUE THREAD

**Issue by Gottay** [OwenLeng/RvNN-pytorch#1]
Hi, I'm really sorry to bother you that I'm a beginner to Pytorch. Your work with pytorch for the paper “Rumor Detection on Twitter with Tree-structured Recursive Neural Networks” do help me a lot. However, I found that there was just BU_RvNN model, and I really also want to learn the TD_RvNN model of pytorch version. Could you please share your source code with me if it is convenient for you?  
P.s. Here is my email adress: gotta_yangyayi@163.com

**Comment by OwenLeng** [comment]
Thanks for your support with regard to my work. However, Sorry, the version of the TD_RvNN model with Pytorch hasn't been written.&nbsp;




冷俊成
965450431@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OwenLeng/RvNN-pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月12日(星期六) 下午5:35
收件人:&nbsp;"OwenLeng/RvNN-pytorch"<RvNN-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OwenLeng/RvNN-pytorch] TD_RvNN pytorch version (#1)





 
Hi, I'm really sorry to bother you that I'm a beginner to Pytorch. Your work with pytorch for the paper “Rumor Detection on Twitter with Tree-structured Recursive Neural Networks” do help me a lot. However, I found that there was just BU_RvNN model, and I really also want to learn the TD_RvNN model of pytorch version. Could you please share your source code with me if it is convenient for you?
